# Copyright 2016 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##API Gateway##
gateway:
  image: amalgam8/a8-sidecar:latest
  environment:
    - A8_CONTROLLER_URL=http://controller:8080
    - A8_REGISTRY_URL=http://registry:8080
    - A8_PROXY=true
    - A8_LOG=true
    - A8_SERVICE=gateway:version=none
    - A8_ELASTICSEARCH_SERVER=elasticsearch:9200
    - A8_CONTROLLER_POLL=5s
    - A8_REGISTRY_POLL=5s
  ports:
    - "32000:6379"
  external_links:
    - elasticsearch
    - controller
    - registry
  container_name: gateway
  command: /usr/bin/run_filebeat.sh

tcphelloworld:
  image: amalgam8/a8-tcp:latest
  environment:
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=tcphelloworld
    - A8_REGISTER=true
    - A8_ENDPOINT_PORT=1111
    - A8_ENDPOINT_TYPE=tcp
  ports:
    - "1111:1111"
  external_links:
    - registry

details-v1:
  image: amalgam8/a8-${A8_TEST_ENV}-bookinfo-details-sidecar-v1:${A8_RELEASE}
  environment:
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=details:version=v1
    - A8_REGISTER=true
    - A8_ENDPOINT_PORT=9080
    - A8_HEALTHCHECKS=http://localhost:9080/health
  external_links:
    - registry

ratings-v1:
  image: amalgam8/a8-${A8_TEST_ENV}-bookinfo-ratings-sidecar-v1:${A8_RELEASE}
  environment:
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=ratings:version=v1
    - A8_REGISTER=true
    - A8_ENDPOINT_PORT=9080
    - A8_HEALTHCHECKS=http://localhost:9080/health
  external_links:
    - registry

reviews-v1:
  image: amalgam8/a8-${A8_TEST_ENV}-bookinfo-reviews-sidecar-v1:${A8_RELEASE}
  environment:
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=reviews:version=v1
    - A8_REGISTER=true
    - A8_ENDPOINT_PORT=9080
    - A8_HEALTHCHECKS=http://localhost:9080/health
  external_links:
    - registry

reviews-v2:
  image: amalgam8/a8-${A8_TEST_ENV}-bookinfo-reviews-sidecar-v2:${A8_RELEASE}
  environment:
    - A8_REGISTER=true
    - A8_PROXY=true
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=reviews:version=v2
    - A8_ENDPOINT_PORT=9080
    - A8_CONTROLLER_URL=http://controller:8080
    - A8_CONTROLLER_POLL=5s
    - A8_REGISTRY_POLL=5s
    - A8_HEALTHCHECKS=http://localhost:9080/health
    - A8_ELASTICSEARCH_SERVER=elasticsearch:9200
  external_links:
    - elasticsearch
    - controller
    - registry

reviews-v3:
  image: amalgam8/a8-${A8_TEST_ENV}-bookinfo-reviews-sidecar-v3:${A8_RELEASE}
  environment:
    - A8_REGISTER=true
    - A8_PROXY=true
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=reviews:version=v3
    - A8_ENDPOINT_PORT=9080
    - A8_CONTROLLER_URL=http://controller:8080
    - A8_CONTROLLER_POLL=5s
    - A8_REGISTRY_POLL=5s
    - A8_HEALTHCHECKS=http://localhost:9080/health
    - A8_ELASTICSEARCH_SERVER=elasticsearch:9200
  external_links:
    - elasticsearch
    - controller
    - registry

productpage-v1:
  image: amalgam8/a8-${A8_TEST_ENV}-bookinfo-productpage-sidecar-v1:${A8_RELEASE}
  environment:
    - A8_REGISTER=true
    - A8_PROXY=true
    - A8_REGISTRY_URL=http://registry:8080
    - A8_SERVICE=productpage:version=v1
    - A8_ENDPOINT_PORT=9080
    - A8_CONTROLLER_URL=http://controller:8080
    - A8_CONTROLLER_POLL=5s
    - A8_REGISTRY_POLL=5s
    - A8_HEALTHCHECKS=http://localhost:9080/health,file:///bin/ls
    - A8_ELASTICSEARCH_SERVER=elasticsearch:9200
  ports:
    - "12345:12345"
  external_links:
    - elasticsearch
    - controller
    - registry
