# Copyright 2016 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: v1
kind: ReplicationController
metadata:
  name: details-v1
  labels:
    name: details-v1
spec:
  replicas: 1
  selector:
    name: details-v1
  template:
    metadata:
      labels:
        name: details-v1
    spec:
      containers:
      - name: details
        image: amalgam8/a8-examples-bookinfo-details:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: servicereg
        image: amalgam8/a8-sidecar:0.2-alpine
        imagePullPolicy: IfNotPresent
        args:
          - --proxy=false
          - --log=false
          - --supervise=false
        env:
        - name: A8_SERVICE
          value: details:v1
        - name: A8_LOGSTASH_SERVER
          value: "'$(LOGSERVER_SERVICE_HOST):8092'"
        - name: A8_REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: A8_REGISTRY_TOKEN
          value: local
        - name: A8_ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: A8_ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ratings-v1
  labels:
    name: ratings-v1
spec:
  replicas: 1
  selector:
    name: ratings-v1
  template:
    metadata:
      labels:
        name: ratings-v1
    spec:
      containers:
      - name: ratings
        image: amalgam8/a8-examples-bookinfo-ratings:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: servicereg
        image: amalgam8/a8-sidecar:0.2-alpine
        imagePullPolicy: IfNotPresent
        args:
          - --proxy=false
          - --log=false
          - --supervise=false
        env:
        - name: A8_SERVICE
          value: ratings:v1
        - name: A8_LOGSTASH_SERVER
          value: "'$(LOGSERVER_SERVICE_HOST):8092'"
        - name: A8_REGISTRY_URL
          value: http://$(REGISTRY_SERVICE_HOST):$(REGISTRY_SERVICE_PORT)
        - name: A8_REGISTRY_TOKEN
          value: local
        - name: A8_ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: A8_ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v1
  labels:
    name: reviews-v1
spec:
  replicas: 1
  selector:
    name: reviews-v1
  template:
    metadata:
      labels:
        name: reviews-v1
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_TENANT_TOKEN
          value: local
        - name: A8_SERVICE
          value: reviews:v1
        - name: A8_LOGSTASH_SERVER
          value: "'$(LOGSERVER_SERVICE_HOST):8092'"
        - name: A8_ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: A8_ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v2
  labels:
    name: reviews-v2
spec:
  replicas: 1
  selector:
    name: reviews-v2
  template:
    metadata:
      labels:
        name: reviews-v2
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_TENANT_TOKEN
          value: local
        - name: A8_SERVICE
          value: reviews:v2
        - name: A8_LOGSTASH_SERVER
          value: "'$(LOGSERVER_SERVICE_HOST):8092'"
        - name: A8_ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: A8_ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v3
  labels:
    name: reviews-v3
spec:
  replicas: 1
  selector:
    name: reviews-v3
  template:
    metadata:
      labels:
        name: reviews-v3
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_TENANT_TOKEN
          value: local
        - name: A8_SERVICE
          value: reviews:v3
        - name: A8_LOGSTASH_SERVER
          value: "'$(LOGSERVER_SERVICE_HOST):8092'"
        - name: A8_ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: A8_ENDPOINT_PORT
          value: "9080"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: productpage-v1
  labels:
    name: productpage-v1
spec:
  replicas: 1
  selector:
    name: productpage-v1
  template:
    metadata:
      labels:
        name: productpage-v1
    spec:
      containers:
      - name: productpage
        image: amalgam8/a8-examples-bookinfo-productpage:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:0.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_TENANT_TOKEN
          value: local
        - name: A8_SERVICE
          value: productpage:v1
        - name: A8_LOGSTASH_SERVER
          value: "'$(LOGSERVER_SERVICE_HOST):8092'"
        - name: A8_ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: A8_ENDPOINT_PORT
          value: "9080"
